# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_transfer.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'file_transfer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66ile_transfer.proto\x12\rfile_transfer\"\x1f\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\".\n\tFileChunk\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"!\n\x0eUploadResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x0e\n\x0c\x45mptyRequest\"%\n\x10\x46ileListResponse\x12\x11\n\tfilenames\x18\x01 \x03(\t2\xe9\x01\n\x0b\x46ileService\x12G\n\nUploadFile\x12\x18.file_transfer.FileChunk\x1a\x1d.file_transfer.UploadResponse(\x01\x12\x46\n\x0c\x44ownloadFile\x12\x1a.file_transfer.FileRequest\x1a\x18.file_transfer.FileChunk0\x01\x12I\n\tListFiles\x12\x1b.file_transfer.EmptyRequest\x1a\x1f.file_transfer.FileListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_transfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=38
  _globals['_FILEREQUEST']._serialized_end=69
  _globals['_FILECHUNK']._serialized_start=71
  _globals['_FILECHUNK']._serialized_end=117
  _globals['_UPLOADRESPONSE']._serialized_start=119
  _globals['_UPLOADRESPONSE']._serialized_end=152
  _globals['_EMPTYREQUEST']._serialized_start=154
  _globals['_EMPTYREQUEST']._serialized_end=168
  _globals['_FILELISTRESPONSE']._serialized_start=170
  _globals['_FILELISTRESPONSE']._serialized_end=207
  _globals['_FILESERVICE']._serialized_start=210
  _globals['_FILESERVICE']._serialized_end=443
# @@protoc_insertion_point(module_scope)
